# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joiner',
            field=models.ManyToManyField(related_name='joined', to='travel_buddy.User'),
        ),
    ]
